[global_tags]
[agent]
  interval = "300s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["http://changeme"]
  database = "system_metrics"
  username = "changeme"
  password = "changeme"
  retention_policy = ""
  timeout = "5s"
[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false
  fieldpass = ["usage_active", "usage_iowait", "usage_system", "usage_user"]
  report_active = true
[[inputs.mem]]
  fieldpass = ["free", "swap_free"]
[[inputs.swap]]
  fieldpass = ["free"]
[[inputs.disk]]
  mount_points = ["/"]
  ignore_fs = ["tmpfs", "devtmpfs"]
  fieldpass = ["free", "used_percent"]
[[inputs.diskio]]
  devices = ["mmcblk0"]
[[inputs.nstat]]
  fieldpass = [
    "IpExtInOctets", 
    "IpExtOutOctets", 
    "TcpExtTCPTimeouts", 
    "TcpExtTCPSynRetrans", 
    "TcpExtTCPLostRetransmit"
  ]
[[inputs.system]]
[[inputs.exec]]
  commands = ["cat /sys/class/thermal/thermal_zone0/temp"]
  data_format = "value"
  data_type = "integer"
  name_override = "cpu_temperature_raw"
[[processors.starlark]]
  namepass = ["nstat"]
  source = '''
def apply(metric):
    in_val = metric.fields.get("IpExtInOctets")
    out_val = metric.fields.get("IpExtOutOctets")
    if in_val == None:
        return None
    if out_val == None:
        return None
    return metric
'''
[[inputs.exec]]
  commands = ["bash -c '[ \"$(systemctl show telegraf.service --property=ActiveState --value)\" = \"active\" ] && echo 1 || echo 0'"]
  data_format = "value"
  data_type = "integer"
  name_override = "service_telegraf"
[[inputs.exec]]
  commands = ["bash -c '[ \"$(systemctl show influxd.service --property=ActiveState --value)\" = \"active\" ] && echo 1 || echo 0'"]
  data_format = "value"
  data_type = "integer"
  name_override = "service_influxd"
[[inputs.exec]]
  commands = ["bash -c '[ \"$(systemctl show rbtempapi.service --property=ActiveState --value)\" = \"active\" ] && echo 1 || echo 0'"]
  data_format = "value"
  data_type = "integer"
  name_override = "service_rbtempapi"
[[inputs.exec]]
  commands = ["bash -c '[ \"$(systemctl show influx-sync.service --property=ActiveState --value)\" = \"active\" ] && echo 1 || echo 0'"]
  data_format = "value"
  data_type = "integer"
  name_override = "service_influx_sync"
[[inputs.exec]]
  commands = ["bash -c '[ \"$(systemctl show iot-reverse-tunnel.service --property=ActiveState --value)\" = \"active\" ] && echo 1 || echo 0'"]
  data_format = "value"
  data_type = "integer"
  name_override = "service_reverse_tunnel"
